server:
  port: 8081

host:
  database: localhost:5432/demo

spring:
  profiles:
    active: local
  datasource:
    dataSourceClassName: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://${host.database}